### ISSUE TITLE
TODO 03.08.2016

### ISSUE THREAD

**Issue by hushchyn-mikhail** [skygrid/grid_simulation#11]
1. Презентация: добавить начало, и картинки в конце.
2. Графики:
   Workload Management System (WMS):
3. [x]  Время выполнения задач: (T_completed - T_submitted)
4. [x] Время планировки задачи: (T_scheduling_end - T_scheduling_start)
5. [ ] Job execution rate per site (daily) (?)
6. [x] Number of running jobs per site (daily)
7. [ ]  Number of waiting jobs per site (daily) (?)
8. [x] Job CPU efficiency 

Data Management System (DMS):
- [x] Total number of datasets on disks/tapes per site (daily)
- [x] Total occupied space on disks/tapes per site (daily)

Network Communication (connected with DMS):
- [x] Cumulative input/output data per site (daily)
- [x] Cumulative transferred data (daily) (?)
- [x] Network load (daily)

Anomalies and Failures:
- [ ] Number of job reschedulers (daily)
- [x] Number of job failures per site (daily)
- [x] Transfer failures per site (daily)
1. Задать вопрос Саше про число свободных ядер для нового запроса. (Миша)
