### ISSUE TITLE
TODO 10.08.2016

### ISSUE THREAD

**Issue by hushchyn-mikhail** [skygrid/grid_simulation#12]
- [x] Исправить флопсы задач (они меньше, чем нужно).
- [x] Исправить графики по джобам. Разобраться в резком росте графика.
- [x] Исправить аномалии.
- [x] Добавить графики по количеству передаваемых данных.
- [ ] Разобраться в планировании задач с учетом данных. (Миша)
- [ ] Узнать о переполнении буфера данных в T2. (Миша)

**Comment by anaderi** [comment]
поменял в описании формат списка, чтобы было проще следить за тем, что сделано

**Comment by kenenbek** [comment]
Здесь можно посмотреть картинки.

https://github.com/skygrid/grid_simulation/blob/master/Plots/Plots.ipynb
